### ISSUE TITLE
Consider re-doing and/or simplifying this video

### ISSUE THREAD

**Issue by matbalez** [learn-co-curriculum/ruby-lecture-reading-error-messages#12]
- rspec is being used but never previously introduced. Previously user has been shown that we run tests with `learn`. Why even use rspec here? 
- video would be cleaner without the typo at 7:45
- With my new user hat on, I find the very rapid overview of the Rspec DSL to be confusing. Making the tests fail by passing the incorrect error type object seems like a fairly advanced concept at this early stage. Personally I think discussion of Rspec can be punted down the field for a while, but if we feel strongly about introducing it here I feel like the notion of a failing test could be better shown with a simpler expectation (maybe like expected the sum of two numbers to be the correct value). Much less abstract than an error object being of the incorrect type. 

cc @AnnJohn

**Comment by loganhasson** [comment]
:+1: to this. i'm just going through this for the first time now, and that part of the video kind of came out of left field for me and got confusing.

**Comment by PeterBell** [comment]
Hey @matbalez and @loganhasson great feedback - thanks very much. This is a substantial change, so I'm gonna get @aviflombaum involved with the discussion in addition to @AnnJohn. My goal is to build a short list of substantive changes requested after triaging these this week and then we'll try to sit down next week and discuss. Thanks.

**Comment by pletcher** [comment]
Hey @PeterBell, what's the status of this issue?

**Comment by PeterBell** [comment]
Hi @pletcher it's pending. I was going through doing triage, so anything like this that required substantial effort I wanted to batch so someone could go ask Avi to "sit down, shoot 12 videos".

**Comment by PeterBell** [comment]
Are you OK taking it from here or would you like me to do anything/be involved? Just let me know . . .

**Comment by pletcher** [comment]
I just wanted to check in on the video tag : ) I'm not sure that I need to be involved with the videos (happy to help, though!) -- just let me know. But your plan sounds good

**Comment by PeterBell** [comment]
I'd say @AnnJohn might be the right person to coordinate these? Ann, let us know. My goal is to provide assists on curriculum, and later this week I'm going to try to get back to doing some triage on it, but I'm guessing Ann would then coordinate and prioritize things like the video re-shoots, although just let me know if you'd like me to be more involved in some way!
