### ISSUE TITLE
ID_RSA

### ISSUE THREAD

**Issue by Terco30** [learn-co-curriculum/ruby-lecture-reading-error-messages#23]
Hi guys, trying to fork/clone this repository

it keeps asking me for a SSH key "id_rsa" and the Learn button to open just runs something on terminal and outputs this:

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require': /usr/local/rvm/gems/ruby-2.2.3/gems/learn-co-3.2.18/lib/learn/options_sanitizer.rb:123: syntax error, unexpected ',' (SyntaxError)
    def rebuild_args!(flag_arg:, add_test_command:)
                                ^
/usr/local/rvm/gems/ruby-2.2.3/gems/learn-co-3.2.18/lib/learn/options_sanitizer.rb:221: syntax error, unexpected keyword_end, expecting end-of-input
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-co-3.2.18/lib/learn.rb:7:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/learn-co-3.2.18/bin/learn:3:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/learn:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/learn:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
logout

I tried uninstalling Learn/reinstalling it and I'm not sure whats wrong!

**Comment by AnnJohn** [comment]
Hi @Terco30 sorry for the trouble. Since it looks like you need immediate help, please use the Ask a Question tool in Learn and someone from our support team will get back to you. Thanks.
