### ISSUE TITLE
unable to proceed to the next lesson

### ISSUE THREAD

**Issue by Tejaswini1393** [learn-co-curriculum/ruby-lecture-reading-error-messages#28]
I had edited all errors and commited the code but still I'm unable to proceed to next lesson.

**Comment by AnnJohn** [comment]
Hi @Tejaswini1393 were all your tests passing and where you able to properly submit the lab? There might be some specific errors, so please use the Ask a Question tool in Learn and someone from our support team will help you out right away. Thanks!
