### ISSUE TITLE
Can't connect to Nitrous

### ISSUE THREAD

**Issue by liasonwithtragedy** [learn-co-curriculum/ruby-lecture-reading-error-messages#29]
Hi. Every time I click on the open button to get into Nitrous I get the following error message:

"Failed to login via ssh. Have you added learn..co's public key to your nitrous container?"

**Comment by AnnJohn** [comment]
Hi @liasonwithtragedy sorry for the trouble that you're having. This looks like it's a bug. If you hover your profile pic in Learn, you'll see an option to Report a Bug. If you could file a bug report that would be great. 

Also you can use the Ask a Question tool in Learn and someone from our support team will help you right away. Thanks!
