### ISSUE TITLE
Additional Lab

### ISSUE THREAD

**Issue by eleanorgraham** [learn-co-curriculum/ruby-lecture-reading-error-messages#31]
I would love to see an additional lab here that takes the same four errors and buries them in a larger chunk of code. That way learners would get the satisfaction of reading the location in the error message and finding them in order to correct them. Thank you for the excellent curriculum!

**Comment by PeterBell** [comment]
Hi @eleanorgraham thanks so much for reaching out with the feedback - very much appreciated! At this point in the curriculum, we're trying to make the error messages accessible, so we've deliberately decided to make this as easy as possible. But don't worry - there are plenty of later labs where you'll definitely *wish* the error messages were easier to read! Thanks again for the input - very much appreciated!
