### ISSUE TITLE
Issue with Learn IDE

### ISSUE THREAD

**Issue by mtferris11** [learn-co-curriculum/ruby-lecture-reading-error-messages#35]
Hi,
I am having trouble with the lesson on reading error messages. I've spoken to a couple of users and it seems that I am missing a few files in my learn IDE. Another user reported a similar problem: 

"TRIPSCRIPTS SAID 17 HOURS AGO
I had the same problem yesterday. had to restart system, then open the lesson from my browser history. some kinda bug!"

Would appreciate any guidance you might have in terms of how I can solve this issue, I have already tried restarting learn/atom/my computer as well as reinstalling learn IDE.

Many thanks,
Maria

**Comment by AnnJohn** [comment]
hi @mtferris11 apologies for the delay. If this is still an issue could you please file a bug report (if you click on your profile pic in Learn, you'll see an option to report a bug). Likewise you can also use the Ask a Question tool; thanks!
