### ISSUE TITLE
Reading Error Messages

### ISSUE THREAD

**Issue by vkulumba** [learn-co-curriculum/ruby-lecture-reading-error-messages#38]
Good evening, 

I'm wondering if there is a way to start the lesson over, I was sent the files to fix via Git, but Learn was not connecting the files under the repository. I received the files two days after beginning to attempt the lab. Is there anyway I can start the lesson over and re-fork?

Best,
Vivian

**Comment by AnnJohn** [comment]
hi @vkulumba i don't think you can re-fork the lesson on your current computer, but you can also delete what you have in the files and just go from there. Thanks!
