### ISSUE TITLE
Forking

### ISSUE THREAD

**Issue by akeeeshi** [learn-co-curriculum/ruby-lecture-reading-error-messages#39]
I keep trying to fork but the learn.co application will not give me the green circle for doing so. I have the other two subsequent aspects of the lesson including the pull submitted and marked as complete but the fork is not doing that no matter how much I try.

**Comment by AnnJohn** [comment]
hi @akeeeshi sorry for the trouble that you're having. Since this is a product issue, could you file a bug report? If you hover over your profile pic in Learn, you'll see an option to Report a Bug. Thanks!
