### ISSUE TITLE
lesson not completed?

### ISSUE THREAD

**Issue by bplatter** [learn-co-curriculum/ruby-lecture-reading-error-messages#42]
I have completed this lesson, run learn with no errors and then entered learn submit, but when I tried to click next lesson it said I haven't completed this message.  On the right it shows that I didn't run local tests or submit pull request.

How do I get this to show as completed?

**Comment by AnnJohn** [comment]
hi @bplatter sorry about this. Since this is a product issue, could you file a bug report (if you click on your profile pic in Learn, you'll see an option to Report a Bug). Also you can use Ask a Question and someone from our team will help you out. Thanks!
