### ISSUE TITLE
ruby-lecture-reading-error-messages

### ISSUE THREAD

**Issue by scottyj6230** [learn-co-curriculum/ruby-lecture-reading-error-messages#44]
Hi,

When i click open in the lesson, the lab isnt being added to the column on the right hand side of my editor.

i can use the terminal to run commands but I can't select the files to edit them.

Thank you

Scott

**Comment by Joll59** [comment]
@scottyj6230 this looks like a bug with your IDE setup please email support@flatironschool.com or refer to our help center here: http://help.learn.co/the-learn-ide
