### ISSUE TITLE
Cannot connect to Learn IDE for this lab

### ISSUE THREAD

**Issue by xhe518** [learn-co-curriculum/ruby-lecture-reading-error-messages#47]
[Before submitting, please enter steps to reproduce:]

_1. Click "OPEN IDE" from the top of the page
2. Observe that connection cannot be established with the following error message_

**Learn IDE Package**: 2.5.3
**Learn IDE Core**: 2.5.3 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [learn-ide-tree](https://github.com/learn-co/learn-ide-tree) package 1.0.23

### Stack Trace

Uncaught TypeError: Cannot read property 'reset' of undefined

```
At C:\Users\Sid\AppData\Local\learn_ide\app-2.5.3\resources\app.asar\node_modules\nsync-fs\lib\connection.js:49

TypeError: Cannot read property 'reset' of undefined
    at Connection.module.exports.Connection.reset (/app.asar/node_modules/nsync-fs/lib/connection.js:49:23)
    at Nsync.resetConnection (/app.asar/node_modules/nsync-fs/lib/nsync-fs.js:86:28)
    at /app.asar/node_modules/learn-ide-tree/lib/nsync/initializer.js:161:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at /app.asar/node_modules/learn-ide/lib/views/status.js:70:34)
```

### Commands

```
     -0:32.7.0 learn-ide:reset-connection (atom-workspace.workspace.scrollbars-visible-always.compact-tab-bar.no-tab-min-width.panel-shadows.panel-contrast.use-animations.compact-tree-view.paint-cursor.theme-atom-material-syntax.theme-learn-ide-material-ui)
```

### Non-Core Packages

```

```

**Comment by sgharms** [comment]
@xhe518 

We have upgraded the web IDE. Please attempt this challenge again. If your issue persists, please report another **awesome** debug session and stack trace to support@flatironschool.com

**Comment by xhe518** [comment]
I reset some browser setting and the issue was solved. Thanks for the
follow up!

**Comment by sgharms** [comment]
@xhe518 Glad to hear it! Enjoy!
