### ISSUE TITLE
Requesting bookmarks

### ISSUE THREAD

**Issue by thierryu** [learn-co-curriculum/ruby-lecture-reading-error-messages#50]
I clicked on the "raise issue" button seeking to bookmark a course section. I suspect this isn't the place for this comment. Please advise.

**Comment by morgvanny** [comment]
Ah, I can see why the icon may make it easy to confuse the 2. Raising an issue is for when there is a problem with the curriculum, or a suggestion for improvement. Your browser should have a way to bookmark the page above the page itself. In Chrome, you can click the star icon on the far right side of the search bar.
