### ISSUE TITLE
Not exactly sure what i'm supposed to do with this lab - and I read the whole thing... 

### ISSUE THREAD

**Issue by guerilla17** [learn-co-curriculum/ruby-lecture-reading-error-messages#51]

**Comment by jenmyers** [comment]
Hello!

It looks like this isn't a bug in the curriculum, but a misunderstanding you
have with the material. That's no problem though! Go ahead and hit the Ask A
Question button on learn.co. Either a community member or a technical coach
will be able to help you understand it.

Good luck!
